name = "RFFT"
uuid = "3645faec-0534-4e91-afef-021db0981eec"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "1.0.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
FFTW = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
